services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      POSTGRES_USER: <%= ENV['POSTGRES_USER'] %>
      POSTGRES_PASSWORD: <%= ENV['POSTGRES_PASSWORD'] %>
      DATABASE_HOST: <%= ENV['DATABASE_HOST'] %>
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true  # デバッガーでのインタラクティブなセッションが可能になります
    stdin_open: true  # Dockerコンテナの標準入力を開く