services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DATABASE_HOST: dpg-crklqcm8ii6s738293e0-a.singapore-postgres.render.com # Render のホスト名
      DATABASE_NAME: db_kduk
      DATABASE_URL: postgresql://db_kduk_user:2YKG0P4pE4hCDNQF6rkxAktm8qottJTO@dpg-crklqcm8ii6s738293e0-a.singapore-postgres.render.com/db_kduk
      POSTGRES_USER: db_kduk_user
      POSTGRES_PASSWORD: 2YKG0P4pE4hCDNQF6rkxAktm8qottJTO
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true  # デバッガーでのインタラクティブなセッションが可能になります
    stdin_open: true  # Dockerコンテナの標準入力を開く
