databases:
  - name: portfolio
    databaseName: db
    user: db_kduk_user
    plan: free
    region: singapore

services:
  - type: web
    name: portfolio
    runtime: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: portfolio
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
      #- key: RAILS_ENV
        #value: production
      